#!/usr/bin/env sh
set -eu

PUBLIC_IP="${PUBLIC_IP:-47.104.158.30}"
ENV_FILE="${ENV_FILE:-.env}"

if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists; leaving it unchanged."
  exit 0
fi

if command -v openssl >/dev/null 2>&1; then
  SECRET_KEY="$(openssl rand -hex 32)"
else
  SECRET_KEY="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)"
fi

cat >"$ENV_FILE" <<EOF
# Frontend
NEXT_PUBLIC_API_BASE_URL=http://${PUBLIC_IP}:8011/api

# Backend
SCREENPULSE_SECRET_KEY=${SECRET_KEY}
SCREENPULSE_DATABASE_URL=sqlite:///./storage/screenpulse.db
SCREENPULSE_CORS_ORIGINS=http://${PUBLIC_IP}:3001
SCREENPULSE_STORAGE_DIR=storage
SCREENPULSE_ACCESS_TOKEN_EXPIRE_HOURS=12
SCREENPULSE_DEFAULT_SAMPLING_INTERVAL_MINUTES=5
SCREENPULSE_MAX_FRAME_UPLOAD_BYTES=5242880
SCREENPULSE_MAX_FRAME_PIXELS=8294400
SCREENPULSE_INVITE_CODE_MAX_USES=25
SCREENPULSE_AUTH_RATE_LIMIT_ATTEMPTS=10
SCREENPULSE_AUTH_RATE_LIMIT_WINDOW_SECONDS=60

# Optional OpenAI-compatible multimodal endpoint
# Example: http://host.docker.internal:1234/v1
SCREENPULSE_MODEL_API_BASE_URL=
SCREENPULSE_MODEL_API_KEY=
SCREENPULSE_VISION_MODEL=
SCREENPULSE_SUMMARY_MODEL=

# Optional LiveKit credentials
SCREENPULSE_LIVEKIT_URL=
SCREENPULSE_LIVEKIT_API_KEY=
SCREENPULSE_LIVEKIT_API_SECRET=
EOF

echo "Created $ENV_FILE for ${PUBLIC_IP}."
